[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "18.14.0"

[context.deploy-preview]
command = "npm run build"

[context.branch-deploy]
command = "npm run build"
